version: '3'

services:
  nginx:
    image: alidemirsoy/nginx:final
    ports:
      - 8080:8080
    links:
      - trading-service
    depends_on:
      - trading-service
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devdb
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
  trading-service:
    image: alidemirsoy/tradingservice:final
    restart: always
    depends_on:
      - mysql
    ports:
      - 9000:9000

